// Generated by gencpp from file movement/serviceTestResponse.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MESSAGE_SERVICETESTRESPONSE_H
#define MOVEMENT_MESSAGE_SERVICETESTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace movement
{
template <class ContainerAllocator>
struct serviceTestResponse_
{
  typedef serviceTestResponse_<ContainerAllocator> Type;

  serviceTestResponse_()
    : sum(0.0)  {
    }
  serviceTestResponse_(const ContainerAllocator& _alloc)
    : sum(0.0)  {
  (void)_alloc;
    }



   typedef float _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::movement::serviceTestResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement::serviceTestResponse_<ContainerAllocator> const> ConstPtr;

}; // struct serviceTestResponse_

typedef ::movement::serviceTestResponse_<std::allocator<void> > serviceTestResponse;

typedef boost::shared_ptr< ::movement::serviceTestResponse > serviceTestResponsePtr;
typedef boost::shared_ptr< ::movement::serviceTestResponse const> serviceTestResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement::serviceTestResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement::serviceTestResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement::serviceTestResponse_<ContainerAllocator1> & lhs, const ::movement::serviceTestResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement::serviceTestResponse_<ContainerAllocator1> & lhs, const ::movement::serviceTestResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::movement::serviceTestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement::serviceTestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement::serviceTestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement::serviceTestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement::serviceTestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement::serviceTestResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement::serviceTestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f720a7bfc448e377e8e2dd877c1aef43";
  }

  static const char* value(const ::movement::serviceTestResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf720a7bfc448e377ULL;
  static const uint64_t static_value2 = 0xe8e2dd877c1aef43ULL;
};

template<class ContainerAllocator>
struct DataType< ::movement::serviceTestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement/serviceTestResponse";
  }

  static const char* value(const ::movement::serviceTestResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement::serviceTestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 sum\n"
;
  }

  static const char* value(const ::movement::serviceTestResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement::serviceTestResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct serviceTestResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement::serviceTestResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement::serviceTestResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<float>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_MESSAGE_SERVICETESTRESPONSE_H
