import { Run } from './interfaces';

export const RUNS: Run[][] = [
  [
    {
      Id: 1,
      Name: 'xy',
      Driver: 'Tom',
      PipeID: 'xyzf',
      direction: 'SSW',
      lat: 20,
      long: 0,
      tag: [
        {
          Id: 1,
          Lat: 0,
          Longi: 0,
        },
        {
          Id: 2,
          Lat: 1,
          Longi: 0,
        },
        {
          Id: 3,
          Lat: 0,
          Longi: 1,
        },
        {
          Id: 4,
          Lat: 1,
          Longi: 1,
        },
      ],
    },
    {
      Id: 2,
      Name: 'x',
      Driver: 'Tom',
      PipeID: 'xyzf',
      direction: 'SSW',
      lat: 20,
      long: 0,
    },
    {
      Id: 3,
      Name: 'xz',
      Driver: 'Tom',
      PipeID: 'xyzf',
      direction: 'SSW',
      lat: 20,
      long: 0,
    },
  ],
  [
    {
      Id: 4,
      Name: 'xy',
      Driver: 'Tom',
      PipeID: 'xyzf',
      direction: 'SSW',
      lat: 20,
      long: 0,
    },
    {
      Id: 5,
      Name: 'x',
      Driver: 'Tom',
      PipeID: 'xyzf',
      direction: 'SSW',
      lat: 20,
      long: 0,
    },
    {
      Id: 6,
      Name: 'xz',
      Driver: 'Tom',
      PipeID: 'xyzf',
      direction: 'SSW',
      lat: 20,
      long: 0,
    },
  ],
  [
    {
      Id: 7,
      Driver: 'Tom',
      PipeID: 'xyzf',
      direction: 'SSW',
      lat: 20,
      long: 0,
    },
    {
      Id: 8,
      Driver: 'Tom',
      PipeID: 'xyzf',
      direction: 'SSW',
      lat: 20,
      long: 0,
    },
    {
      Id: 9,
      Driver: 'Tom',
      PipeID: 'xyzf',
      direction: 'SSW',
      lat: 20,
      long: 0,
    },
  ],
  [
    {
      Id: -1,
      Name: 'xyz',
      Driver: 'Tom',
      PipeID: 'xyzf',
      direction: 'SSW',
      lat: 20,
      long: 0,
    },
  ],
];
