; Auto-generated. Do not edit!


(cl:in-package diff_drive-msg)


;//! \htmlinclude GoToPoseFeedback.msg.html

(cl:defclass <GoToPoseFeedback> (roslisp-msg-protocol:ros-message)
  ((processing
    :reader processing
    :initarg :processing
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass GoToPoseFeedback (<GoToPoseFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GoToPoseFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GoToPoseFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name diff_drive-msg:<GoToPoseFeedback> is deprecated: use diff_drive-msg:GoToPoseFeedback instead.")))

(cl:ensure-generic-function 'processing-val :lambda-list '(m))
(cl:defmethod processing-val ((m <GoToPoseFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader diff_drive-msg:processing-val is deprecated.  Use diff_drive-msg:processing instead.")
  (processing m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GoToPoseFeedback>) ostream)
  "Serializes a message object of type '<GoToPoseFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'processing) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GoToPoseFeedback>) istream)
  "Deserializes a message object of type '<GoToPoseFeedback>"
    (cl:setf (cl:slot-value msg 'processing) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GoToPoseFeedback>)))
  "Returns string type for a message object of type '<GoToPoseFeedback>"
  "diff_drive/GoToPoseFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GoToPoseFeedback)))
  "Returns string type for a message object of type 'GoToPoseFeedback"
  "diff_drive/GoToPoseFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GoToPoseFeedback>)))
  "Returns md5sum for a message object of type '<GoToPoseFeedback>"
  "14c43fbec2ed75ad470309f9d3538198")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GoToPoseFeedback)))
  "Returns md5sum for a message object of type 'GoToPoseFeedback"
  "14c43fbec2ed75ad470309f9d3538198")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GoToPoseFeedback>)))
  "Returns full string definition for message of type '<GoToPoseFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%bool processing~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GoToPoseFeedback)))
  "Returns full string definition for message of type 'GoToPoseFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%bool processing~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GoToPoseFeedback>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GoToPoseFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'GoToPoseFeedback
    (cl:cons ':processing (processing msg))
))
